kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - git clone https://github.com/unsortedArray/TestCases1.git
  - cd TestCases1
  - npm install -g mocha
  - npm -g install chai
  - npm -g install chai-http
  - npm -g install mochawesome
  - mocha test.js --reporter mochawesome --exit
  - cat /drone/src/TestCases1/mochawesome-report/mochawesome.json