kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - git clone https://github.com/unsortedArray/TestCases1.git
  - cd TestCases1
  - npm install -g mocha
  - npm -g install chai
  - npm -g install chai-http
  - mocha --version
  - mocha test.js --exit