kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - node index.js

kind: pipeline
name: newman-test
steps:
- name: testNewman
  image: node
  commands: 
  - npm install -g newman
  - newman --version
  - newman run NS-Node-Eval.postman_collection.json